FROM php:7.4-fpm-alpine

MAINTAINER wenzhaowang <wenzhaowang@51k1k.com>

ARG timezone

ENV TIMEZONE=${timezone:-"Asia/Shanghai"}

# Libs
RUN apk update && \
    apk del libmcrypt && \
    apk add --no-cache make \
                       libc-dev \
                       gcc \
                       g++ \
                       wget \
                       tzdata \
                       libxml2-dev \
                       openssl-dev \
                       sqlite-dev \
                       curl-dev \
                       oniguruma-dev \
                       autoconf \
                       libzip-dev \
                       freetype-dev \
                       libjpeg-turbo-dev \
                       supervisor \
                       libmcrypt \
                       libmcrypt-dev \
                       libevent \
                       libevent-dev \
                       rabbitmq-c \
                       rabbitmq-c-dev \
                       libpng-dev && \
    
    # PHP Library
    docker-php-ext-install zip \
                           pdo \
                           pdo_mysql \
                           opcache \
                           mysqli \
                           bcmath \
                           sockets \
                           pcntl && \
    # PHP Library
    pecl install mcrypt \ 
                 nsq \
                 amqp \
                 swoole-4.8.11 && \
    # Timezone
    cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
    echo "${TIMEZONE}" > /etc/timezone && \
    echo "[Date]\ndate.timezone=${TIMEZONE}" > /usr/local/etc/php/conf.d/timezone.ini && \
    apk del tzdata

# composer
RUN php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ && \

    # Mongo
    pecl install redis mongodb && \
    rm -rf /tmp/pear && \
    docker-php-ext-enable redis mongodb && \

    # GD Library
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
    docker-php-ext-install -j$(nproc) gd && \

    # Clean
    apk del && rm -rf /var/cache/apk/*
    
COPY php.ini /usr/local/etc/php/php.ini
COPY php-fpm.conf /usr/local/etc/
COPY www.conf /usr/local/etc/php-fpm.d/www.conf
